config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("manager.urls"))
]

manager/urls.py
from django.urls import path
from . import views
app_name="manager"
urlpatterns = [    
    path('', views.index_view, name='manager_home'),
    path('menu_list_url/', views.menu_list, name="menu_list_page"),
    path('menu_add_url/',views.menu_add, name="menu_add_page"), # 메뉴 추가 페이지
    path('add_menu_data/', views.add_menu_data, name='add_menu_data'),
    # 메뉴 디테일 페이지 추가
    path('detail/<int:menu_id>/', views.menu_detail, name="menu_detail"),
    path('add_option/<int:menu_id>/', views.add_option, name='add_option'),
    path('add_option_data/', views.add_option_data, name='add_option_data'),
    path('create/', views.create, name="menu_create"),
    path('<int:pk>/update/', views.update, name="menu_update"),
    path('<int:pk>/delete/', views.delete, name="menu_delete"),
]

manager/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    menu_name=models.CharField(max_length=20)
    menu_price=models.IntegerField()
    def __str__(self):
        return self.menu_name

class Option(models.Model):
    menu=models.ForeignKey(Menu, on_delete=models.CASCADE)
    option_name=models.CharField(max_length=20)
    option_price=models.IntegerField()

    def __str__(self) -> str:
        return f"{self.option_name}_{self.option_price}원"

manager/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Menu, Option
from django.urls import reverse

# Create your views here.
def index_view(request):
    return render(request, 'manager/index.html')

def menu_list(request): # Menu Table을 조회해서 메뉴 리스트를 전달해주겠습니다.
    menus = Menu.objects.all()
    context = {
        "menus_to_page" :menus,
        "cafe_name":"사나리아"
    }
    return render(request, 'manager/menu_list_page.html',context)

def menu_add(request):
    return render(request, 'manager/menu_add_page.html')

def add_menu_data(request):
    menu_name_from_form = request.POST['menu_name'] # 받아온 메뉴이름 변수에 담기
    if menu_name_from_form.strip()=='': # 제대로 된 값이 맞는지 검증해서 처리
        context = {"message":"메뉴 이름을 넣으셔야 됩니다."}
        return render(request, 'manager/menu_add_page.html', context)
    menu_price_from_form = request.POST['menu_price'] # 받아온 메뉴가격 변수에 담기
    # Menu 테이블에 가져온 값 저장하기
    Menu.objects.create(menu_name=menu_name_from_form, menu_price=menu_price_from_form)
    print(f"메뉴이름 : {menu_name_from_form}, 가격 : {menu_price_from_form} 이 추가되었습니다. ") # log 추가
    
    return render(request, 'manager/menu_add_page.html') # 이후 단계 페이지 설정

   
def menu_detail(request, menu_id):
    # print("menu_id : ",menu_id)
    menu = Menu.objects.get(pk=menu_id)
    context = {
       "menu_to_page" : menu
    }
    return render(request, 'manager/menu_detail.html', context)

def add_option(request, menu_id):
    menu = Menu.objects.get(pk=menu_id)
    context = {"menu":menu}
    return render(request, 'manager/add_option.html', context)

def add_option_data(request):
    menu_id_from_form = request.POST['menu_id']
    option_name_from_form = request.POST['option_name']
    option_price_from_form = request.POST['option_price']
    # DB Opion Table에 저장
    menu = Menu.objects.get(pk=menu_id_from_form)
    Option.objects.create(menu=menu, option_name=option_name_from_form, option_price=option_price_from_form)
    context = {"menu":menu}
    return render(request, 'manager/add_option.html', context) # option 추가 화면 보여주기

def create(request):
    if request.method =="POST":
        menu_name=request.POST['menu_name']
        menu_price=request.POST['menu_price']
        Menu.objects.create(menu_name=menu_name, menu_price=menu_price)
        return HttpResponseRedirect(reverse('manager:manager_home'))
    # model = Menu
    # success_url = reverse('manager:manager_home')
    elif request.method == "GET":
        return render(request, 'manager/create.html')
    # templates_name = 'manager/create.html'

def update(request, pk): # pk로 구분되는 어떤 대상이 있는 상황
    if request.method =="POST":
        menu_name=request.POST['menu_name']
        menu_price=request.POST['menu_price']
        # Menu.objects.create(menu_name=menu_name, menu_price=menu_price)
        menu = Menu.objects.get(pk=pk)
        menu.menu_name=menu_name
        menu.menu_price=menu_price
        menu.save()        
        return HttpResponseRedirect(reverse('manager:manager_home'))
    # model = Menu
    # success_url = reverse('manager:manager_home')
    elif request.method == "GET":    # 원래 내용을 담는다
        menu = Menu.objects.get(pk=pk)
        context = {
            "menu_name":menu.menu_name,
            "menu_price":menu.menu_price
        }
        return render(request, 'manager/update.html', context)
    
def delete(requst, pk):
    menu = Menu.objects.get(pk=pk)
    menu.delete()
    return HttpResponseRedirect(reverse('manager:menu_list_page')) # success_url

manager/templates/manager/add_option.html
<h1>{{menu.menu_name}}의 옵션을 추가합니다</h1>


<form action="{% url 'manager:add_option_data' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="menu_id" value="{{menu.id}}">
    <label for="">옵션이름</label>
    <input type="text" name="option_name">
    <label for="">옵션가격</label>
    <input type="number" name="option_price" id="">
    <input type="submit" value="옵션추가해서 DB에 넣기">
</form>

<a href="{% url 'manager:manager_home' %}">Home</a>

manager/templates/manager/create.html
<form action="" method="post">
{% csrf_token %}
<label for="">Menu name</label><input type="text" name="menu_name">
<label for="">Menu price</label><input type="number" name="menu_price">
<input type="submit" name="" id="" value="submit">
</form>

manager/templates/manager/index.html
<h1>Cafe 사나리아</h1>
<p>관리자 페이지입니다</p>
<ul>
<li><a href="{% url 'manager:menu_list_page' %}">메뉴리스트</a> </li>
<li><a href="{% url 'manager:menu_add_page' %}">메뉴추가</a> </li>
<li><a href="/admin/">관리자페이지</a> </li>
</ul>
<img src="https://www.indonesia.travel/content/dam/indtravelrevamp/en/trip-ideas/5-jakarta-cafes-every-instagrammer-should-visit/header.jpg" alt="" width="70%" height="auto">

manager/templates/manager/menu_add_page.html
<h1>메뉴 추가 페이지입니다</h1>
<a href="{% url 'manager:manager_home' %}">
    Home
</a>
{% if message %}
<h2>{{message}}</h2>
{% endif %}
<form action="{% url 'manager:add_menu_data' %}" method="post">
    {% csrf_token %}
    <label for="">메뉴이름</label>
    <input type="text" name="menu_name">
    <label for="">메뉴가격</label>
    <input type="number" name="menu_price" id="">
    <input type="submit" value="메뉴추가해서 DB에 넣기">
</form>

manager/templates/manager/menu_detail.html
<h1>{{menu_to_page.menu_name}}</h1>

<ul>
    {% for option in menu_to_page.option_set.all %}
    <li>
        {{option.option_name}} : {{option.option_price}}원
    </li>
    {% endfor %}
</ul>

<a href="{% url 'manager:add_option' menu_to_page.id %}">옵션추가</a>
<a href="{% url 'manager:menu_update' menu_to_page.id %}">업데이트</a>
<a href="{% url 'manager:menu_delete' menu_to_page.id %}">삭제</a>
<a href="{% url 'manager:manager_home' %}"></a>

manager/templates/manager/menu_list_page.html
<h1>{{cafe_name}} 메뉴 리스트</h1>
<a href="{% url 'manager:manager_home' %}">Home</a>

<ul>
{% for menu in menus_to_page %}
<li>
    <a href="{% url 'manager:menu_detail' menu.id %}">{{menu.menu_name}} : {{menu.menu_price}}</a>
</li>
{% endfor %}
</ul>

<a href="{% url 'manager:menu_add_page' %}">메뉴추가</a>
<a href="{% url 'manager:manager_home' %}"></a>

manager/templates/manager/update.html
<form action="" method="post">
    {% csrf_token %}
    <label for="">Menu name</label><input type="text" name="menu_name" value="{{menu_name}}">
    <label for="">Menu price</label><input type="number" name="menu_price" value="{{menu_price}}">
    <input type="submit" name="" id="" value="submit">
    </form>